# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0bhello.proto\x1a google/protobuf/descriptor.proto\"\x1b\n\x05World\x12\x12\n\x04text\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01\"O\n\x05Hello\x12\x1b\n\x08greeting\x18\x01 \x01(\x0e\x32\t.Greeting\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1b\n\x05world\x18\x03 \x01(\x0b\x32\x06.WorldB\x04\x90\xb5\x18\x01*/\n\x08Greeting\x12\x08\n\x04NONE\x10\x00\x12\x06\n\x02MR\x10\x01\x12\x07\n\x03MRS\x10\x02\x12\x08\n\x04MISS\x10\x03:1\n\x08required\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_GREETING = _descriptor.EnumDescriptor(
  name='Greeting',
  full_name='Greeting',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MRS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISS', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=159,
  serialized_end=206,
)
_sym_db.RegisterEnumDescriptor(_GREETING)

Greeting = enum_type_wrapper.EnumTypeWrapper(_GREETING)
NONE = 0
MR = 1
MRS = 2
MISS = 3

REQUIRED_FIELD_NUMBER = 50002
required = _descriptor.FieldDescriptor(
  name='required', full_name='required', index=0,
  number=50002, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_WORLD = _descriptor.Descriptor(
  name='World',
  full_name='World',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='World.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\220\265\030\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=76,
)


_HELLO = _descriptor.Descriptor(
  name='Hello',
  full_name='Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='Hello.greeting', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Hello.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='world', full_name='Hello.world', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\220\265\030\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=157,
)

_HELLO.fields_by_name['greeting'].enum_type = _GREETING
_HELLO.fields_by_name['world'].message_type = _WORLD
DESCRIPTOR.message_types_by_name['World'] = _WORLD
DESCRIPTOR.message_types_by_name['Hello'] = _HELLO
DESCRIPTOR.enum_types_by_name['Greeting'] = _GREETING
DESCRIPTOR.extensions_by_name['required'] = required

World = _reflection.GeneratedProtocolMessageType('World', (_message.Message,), dict(
  DESCRIPTOR = _WORLD,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:World)
  ))
_sym_db.RegisterMessage(World)

Hello = _reflection.GeneratedProtocolMessageType('Hello', (_message.Message,), dict(
  DESCRIPTOR = _HELLO,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:Hello)
  ))
_sym_db.RegisterMessage(Hello)

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(required)

_WORLD.fields_by_name['text'].has_options = True
_WORLD.fields_by_name['text']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\220\265\030\001'))
_HELLO.fields_by_name['world'].has_options = True
_HELLO.fields_by_name['world']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\220\265\030\001'))
# @@protoc_insertion_point(module_scope)
